# https://github.com/cirocosta/sample-grafana/blob/master/grafana/provisioning/datasources/all.yml

apiVersion: 1

datasources:
  -  access: 'proxy'                       # make grafana perform the requests
     editable: true                        # whether it should be editable
     isDefault: true                      # whether this should be the default DS
     name: 'prometheus'                    # name of the datasource
     orgId: 1                             # id of the organization to tie this datasource to
     type: 'prometheus'                    # type of the data source
     url: 'http://prometheus:9090'         # url of the prom instance
     version: 1                            # well, versioning
     jsonData:
        timeInterval: '5s'
