# Read more about AnyCable configuration here: https://docs.anycable.io/ruby/configuration
#
default: &default
  # Turn on/off access logs ("Started..." and "Finished...")
  access_logs_disabled: false
  # Use HTTP adapter for a quick start (since redis gem is not present in the project)
  broadcast_adapter: http
  # WebSocket server URL for clients
  websocket_url: "/cable"
  http_rpc_mount_path: "/_anycable"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  websocket_url: ~
