service: anycable_rails_demo
image: kalashnikovisme/anycable_rails_demo
servers:
  web:
    hosts:
      - 167.99.251.136
    env: 
  anycable:
    hosts:
      - 167.99.251.136
    port: 50051
    cmd: bundle exec anycable
registry:
  username: kalashnikovisme
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  clear:
    ANYCABLE_REDIS_URL: redis://localhost:6379/0
    ANYCABLE_RPC_HOST: 0.0.0.0:50051
    CABLE_URL: ws://localhost:8080/cable
    DB_HOST: 157.230.127.126
  secret:
    - RAILS_MASTER_KEY
    - PG_ROOT_PASSWORD

accessories:
  db:
    image: postgres:15.0
    host: 157.230.127.126
    port: 5432
    env:
      secret:
        - PG_ROOT_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    host: 167.99.251.136
    role:
      - web
    port: "36379:6379"
    volumes:
      - /var/lib/redis:/data

  ws:
    image: anycable/anycable-go:1.2
    port: 8080
    host: 167.99.251.136
    env:
      clear:
        ANYCABLE_HOST: "0.0.0.0"
        ANYCABLE_PORT: 8080
        ANYCABLE_REDIS_URL: redis://localhost:6379/0
        ANYCABLE_RPC_HOST: localhost:50051
