service: anycable_rails_demo
image: kalashnikovisme/anycable_rails_demo
servers:
  web:
    hosts:
      - 167.99.251.136
    env:
      clear: 
        ANYCABLE_RPC_HOST: 64.226.100.79:50051
  anycable:
    hosts:
      - 64.226.100.79
    cmd: bundle exec anycable --log-file=log/production.log --debug
    env:
      clear: 
        ANYCABLE_RPC_HOST: 0.0.0.0:50051
    options:
      publish: "50051:50051"

healthcheck:
  path: /

registry:
  username: kalashnikovisme
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  clear:
    ANYCABLE_REDIS_URL: redis://:bgfjnbjkgnbfguihbfguibjhfgoibjfgoerhordjio@64.226.116.153:6379/0
    CABLE_URL: ws://165.22.65.160:8080/cable
    DB_HOST: 134.209.240.18
    POSTGRES_USER: 'anycable'
    POSTGRES_DB: 'anycable_production'
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - DO_SPACES_KEY
    - DO_SPACES_SECRET
    - DO_SPACES_BUCKET

builder:
  args:
    DO_SPACES_KEY: YOUR_SPACES_KEY
    DO_SPACES_SECRET: YOUR_DO_SPACES_SECRET
    DO_SPACES_BUCKET: YOUR_SPACES_BUCKET
    ANYCABLE_REDIS_URL: redis://:REDIS_PASSWORD@64.226.116.153:6379/0

accessories:
  db:
    image: postgres:15.0
    host: 134.209.240.18
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'anycable'
        POSTGRES_DB: 'anycable_production'
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0.10
    host: 64.226.116.153
    port: 6379
    cmd: redis-server --requirepass REDIS_PASSWORD
    volumes:
      - /var/lib/redis:/data

  ws:
    image: anycable/anycable-go:1.2
    host: 165.22.65.160
    port: "8080:8080"
    env:
      clear:
        ANYCABLE_HOST: "0.0.0.0"
        ANYCABLE_PORT: 8080
        ANYCABLE_REDIS_URL: redis://:REDIS_PASSWORD@64.226.116.153:6379/0
        ANYCABLE_RPC_HOST: 64.226.100.79:50051
        ANYCABLE_DEBUG: true
        ANYCABLE_LOG_LEVEL: debug
