{
 "title": "AnyCable Go",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "anycable_go_clients_num", "legendFormat": "total" },
    { "expr": "anycable_go_clients_uniq_num", "legendFormat": "uniq" }
   ]
  },
  {
   "title": "Go routines number",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "anycable_go_goroutines_num", "legendFormat": "goroutines" }
   ]
  },
  {
   "title": "AnyCable Go Memory",
   "type": "graph",
   "description": "This is memory usage reported by anycable-go itself",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "anycable_go_mem_sys_bytes", "legendFormat": "mem" }
   ]
  },
  {
   "title": "RPC calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(anycable_go_rpc_call_total[$__rate_interval])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(anycable_go_rpc_error_total[$__rate_interval])",
     "legendFormat": "errors"
    },
    {
     "expr": "rate(anycable_go_rpc_retries_total[$__rate_interval])",
     "legendFormat": "retries"
    },
    {
     "expr": "rate(anycable_go_rpc_pending_num[$__rate_interval])",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Total anycable messages broadcasted",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "increase(anycable_go_broadcast_msg_total[$__rate_interval])",
     "legendFormat": "msgs"
    },
    {
     "expr": "increase(anycable_go_failed_broadcast_msg_total[$__rate_interval])",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Client anycable messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(anycable_go_client_msg_total[$__rate_interval])",
     "legendFormat": "msgs"
    },
    {
     "expr": "rate(anycable_go_failed_client_msg_total[$__rate_interval])",
     "legendFormat": "errors"
    }
   ]
  }
 ]
}