{
 "title": "AnyCable (combined)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of clients",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "anycable_go_clients_num", "legendFormat": "total" },
    { "expr": "anycable_go_clients_uniq_num", "legendFormat": "uniq" }
   ]
  },
  {
   "title": "RPC calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(anycable_go_rpc_call_total[$__rate_interval])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(anycable_go_rpc_error_total[$__rate_interval])",
     "legendFormat": "errors"
    },
    {
     "expr": "rate(anycable_go_rpc_retries_total[$__rate_interval])",
     "legendFormat": "retries"
    },
    {
     "expr": "rate(anycable_go_rpc_pending_num[$__rate_interval])",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Total anycable messages broadcasted",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "increase(anycable_go_broadcast_msg_total[$__rate_interval])",
     "legendFormat": "msgs"
    },
    {
     "expr": "increase(anycable_go_failed_broadcast_msg_total[$__rate_interval])",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "RPC call runtime (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(anycable_rpc_call_runtime_seconds_bucket[1m])) by (method,command,le))",
     "legendFormat": "{{method}}: {{command}}"
    }
   ]
  },
  {
   "title": "Client anycable messages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(anycable_go_client_msg_total[$__rate_interval])",
     "legendFormat": "msgs"
    },
    {
     "expr": "rate(anycable_go_failed_client_msg_total[$__rate_interval])",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "RPC call throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(anycable_rpc_call_count[1m])) by (method, command, status)",
     "legendFormat": "{{method}}: {{command}} ({{status}})"
    }
   ]
  },
  {
   "title": "Failed authentication attempts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "anycable_go_failed_auths_total" }
   ]
  },
  {
   "title": "Disconnect queue size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anycable_go_disconnect_queue_size"
    }
   ]
  },
  {
   "title": "AnyCable Go Memory",
   "type": "graph",
   "description": "This is memory usage reported by anycable-go itself",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "anycable_go_mem_sys_bytes", "legendFormat": "mem" }
   ]
  },
  {
   "title": "In/out data",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "anycable_go_data_rcvd_total", "legendFormat": "In (bytes)" },
    { "expr": "anycable_go_data_sent_total", "legendFormat": "Out (bytes)" }
   ]
  },
  {
   "title": "Go routines number",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "anycable_go_goroutines_num", "legendFormat": "goroutines" }
   ]
  }
 ]
}