{
 "title": "Rails / Puma",
 "description": "Basic Rails and Puma metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum(increase(rails_requests_total[1m])) by (status))",
     "legendFormat": "total ({{status}})"
    }
   ]
  },
  {
   "title": "Rails average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_request_duration_seconds_sum[1m]))\n/\nsum(rate(rails_request_duration_seconds_count[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(rails_db_runtime_seconds_sum[1m]))\n/\nsum(rate(rails_db_runtime_seconds_count[1m]))",
     "legendFormat": "db"
    },
    {
     "expr": "sum(rate(rails_view_runtime_seconds_sum[1m]))\n/\nsum(rate(rails_view_runtime_seconds_count[1m]))",
     "legendFormat": "view"
    }
   ]
  },
  {
   "title": "Puma backlog",
   "type": "timeseries",
   "description": "The number of connections waiting for a worker thread",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "sum(puma_backlog)", "legendFormat": "backlog" }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rails_requests_total[1m])) by (controller, action)",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Puma threads utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(puma_max_threads - puma_pool_capacity) / puma_running",
     "legendFormat": "utilization (worker {{ index }})"
    }
   ]
  },
  {
   "title": "Rails 95% response time by endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rails_request_duration_seconds_bucket[1m])) by (le,controller,action))",
     "legendFormat": "{{controller}}#{{action}}"
    }
   ]
  },
  {
   "title": "Puma max threads",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(puma_max_threads)" }
   ]
  },
  {
   "title": "Puma workers",
   "type": "gauge",
   "description": "The total number of Puma workers currently running",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(puma_workers)", "legendFormat": "Total" }
   ]
  }
 ]
}